### PR TITLE
Fix installation link and add quick install

### PR DESCRIPTION
**Pull request by sfmig**
## Description

**What is this PR**

- [x] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**Why is this PR needed?**
Installation link was returning 404

**What does this PR do?**
Fixes installation link and adds quick install instructions. 

## References

\

## How has this PR been tested?

\

## Is this a breaking change?

\

## Does this PR require an update to the documentation?

\

## Checklist:

- [ ] The code has been tested locally
- [ ] Tests have been added to cover all new functionality
- [ ] The documentation has been updated to reflect any changes
- [ ] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Comment by sfmig** [comment]
Questions/suggestions:
- Should we have some automatic link checking for markdown files? 
    - One option would be [in CI](https://github.com/UCL-ARC/python-tooling/blob/main/.github/workflows/links.yml) (action repo [here](https://github.com/lycheeverse/lychee-action)). 
    - Another via pre-commit hooks (for example [this](https://github.com/tcort/markdown-link-check), but there may be better ones). In [a similar discussion](https://github.com/UCL-ARC/python-tooling/issues/310) before, wise people seemed to recommend against pre-commit because of expected flakiness.
    
- Could we include the user installation code snippet in the README? I understand we don't want to have duplicated info to avoid having to edit it in too many places if it changes, but I wonder if in this case is worth the (small?) effort. It feels slightly faffy to redirect people to the docs for just the install command (I would keep the docs link tho in case they have issues or want further details). Maybe just:
	### Quick install
	
	First create and activate a conda environment with the required dependencies:
	```
	conda create -n movement-env -c conda-forge python=3.10 pytables
	conda activate movement-env
	```
	
	Then install the movement package:
	```
	pip install movement
	```
	
	For further details, see the [installation docs](https://movement.neuroinformatics.dev/getting_started/installation.html).

**Comment by adamltyson** [comment]
There's already link checking right via sphinx?

**Comment by sfmig** [comment]
yeah, but I think it doesn't include the repo's README. Is that right @niksirbi?

**Comment by adamltyson** [comment]
Oh yeah, sorry. That is correct (I think).

**Comment by niksirbi** [comment]
I think the two questions are related.
If we keep the README minimal, as is now, I don't see much value in adding more automated checks specifically for it.
If we decide to add more stuff to the README, e.g. the installation instructions that Sofia suggests, additional checks would useful.

I'm undecided on this. I agree that having the installation instructions "right there" in the README is convenient, and commonly done for other tools, but it increases the probability of things getting out of sync. There are some workarounds, like including a specific snippet of text from the README into the docs, but they are hacky and will preclude us from using the fancy sphinx-design elements.

Happy to go with whatever the majority of @neuroinformatics-unit/behaviour thinks...

**Comment by adamltyson** [comment]
My view is:
- Have some additional minimal info in the readme (installation & quickstart)
- Don't add any extra tooling to check it. I expect us to spend more time fixing the tooling rather than just checking the readme every so often.

**Review by niksirbi — APPROVED** [review]
Good to go!

**Pull request merged**
