### PR TITLE
Suggestion to treat warnings as errors in sphinx-build

### PR DESCRIPTION
**Pull request by sfmig**
## Description

**What is this PR**

- [ ] Bug fix
- [ ] Addition of a new feature
- [x] Other -- a suggestion

**Why is this PR needed?**
On issue #252, @lochhh pointed out that `sphinx-build` returns a successful exit code (0) even if it encountered errors.

This can be quite annoying: in practice it means we need to remember to manually check the logs of the docs building action (or locally), to confirm that there were no errors, even if the action shows a pass ✅ . 

For example, in the case @lochhh caught, the docstrings were not rendered correctly in the API reference, but the action was passing.

The [simplest workaround](https://github.com/sphinx-doc/sphinx/issues/10397) seems to add the flags `-W --keep-going` so that `sphinx-build` runs to completion, but treating warnings as errors and returning a non-zero exit code if there are errors or warnings.

**What does this PR do?**

This PR adds the flags `-W --keep-going` to our Makefile. Open to discussion though!

**Question:** 
Should we add these flags to the [neuroinformatics action](https://github.com/neuroinformatics-unit/actions/blob/cb5fa47a94aad675e37bee3d286b412c1b35feac/build_sphinx_docs/action.yml#L71C9-L71C52) too? It may be useful for everyone. If we agree we go for this, I am happy to do it.

## References

- https://github.com/sphinx-doc/sphinx/issues/10397
- #252, and also the PRs mentioned in that issue

## How has this PR been tested?

I manually checked the exit code from `sphinx-build` with and without the proposed flags, in two situations:

- __Case 1: `sphinx-build` returns a warning only__
To reproduce:
	1. I edited the docstring of a user visible function (e.g. `movement.io.load_bboxes`-->`from_numpy`) to indent something under the parameter section. 
	2. I run `make clean html` from the docs directory
	3. That produces a WARNING only: 			 
	```python
	/Users/sofia/swc/project_movement_dataloader/movement/movement/io/load_bboxes.py:docstring of movement.io.load_bboxes.from_numpy:10: WARNING: Field list ends without a blank line; unexpected unindent.
	```
			
- __Case 2: `sphinx-build` returns an error__
To reproduce:
	1. I edited the docstring of a user visible function (e.g. `movement.io.load_bboxes`-->`from_numpy`) to indent something under the main summary line, but before the Parameters section.
	```python
	"""Create a ``movement`` bounding boxes dataset from NumPy arrays.
	
	  Bla
	  - bla   
	      bla
	
	  Parameters
	  ----------
	  ...
	"""
	```
	
	3. I run `make clean html` from the docs directory
	4. That produces an ERROR: 			 
	
	```python
	/Users/sofia/swc/project_movement_dataloader/movement/movement/io/load_bboxes.py:docstring of movement.io.load_bboxes.from_numpy:6: ERROR: Unexpected indentation.
	```

In both cases, if we run `make clean html`
- without any flags to `sphinx-build` in the Makefile ---> I get exit code 0
- with the flags `-W --keep-going` added to `sphinx-build` in the Makefile---> I get exit code 2

## Is this a breaking change?

No.

## Does this PR require an update to the documentation?

I added a comment to the workflow file to clarify

## Checklist:

- [x] The code has been tested locally
- [ n/a ] Tests have been added to cover all new functionality
- [x] The documentation has been updated to reflect any changes
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Review by niksirbi — APPROVED** [review]
I like this @sfmig, that particular loophole has created a few problems for us already and it'd be nice to close.

I'd ask you to also update the `sphinx-build` commands in "Building the documentation locally" section of the contributing guide (under the "All platforms" tabs). The `-W --keep-going` should also be included there in case people cannot (or choose to not) use the `make` command.

I'd also favour updating the corresponding NIU action.

**Comment by sfmig** [comment]
One question to our Make expert @lochhh: 

Should we add the flags `-W --keep-going` to [`SPHINXOPTS`](https://github.com/neuroinformatics-unit/movement/blob/2d553c93b8ad4e8947f58a2937a1e288ec2eab9b/docs/Makefile#L6), rather than [appending](https://github.com/neuroinformatics-unit/movement/blob/2d553c93b8ad4e8947f58a2937a1e288ec2eab9b/docs/Makefile#L33C72-L33C87) them to the sphinx-build command? WDYT?

**Comment by lochhh** [comment]
> One question to our Make expert @lochhh:
> 
> Should we add the flags `-W --keep-going` to [`SPHINXOPTS`](https://github.com/neuroinformatics-unit/movement/blob/2d553c93b8ad4e8947f58a2937a1e288ec2eab9b/docs/Makefile#L6), rather than [appending](https://github.com/neuroinformatics-unit/movement/blob/2d553c93b8ad4e8947f58a2937a1e288ec2eab9b/docs/Makefile#L33C72-L33C87) them to the sphinx-build command? WDYT?

😄 no Make expert, but I think we should use `SPHINXOPTS`, so that in both make and sphinx-build commands in the guide, we consistently have the flags (we can also explain what they do). Alternatively, we can keep the guide as is (throwing only warnings) and only enable these in CI doc build job

**Comment by niksirbi** [comment]
> Alternatively, we can keep the guide as is (throwing only warnings), whilst mentioning the flags (what they do and that they're used in CI) and only enable these in CI doc build job

I'm not a fan of this, as it would results in differences between local build vs CI, which could be confusing during debugging. I think we should try to stick to the rule that local vs CI checks should be as similar as possible.

**Comment by sfmig** [comment]
> and therefore implicitly applies -W --keep-going when a user runs sphinx-build locally, yes.

I think that adding them to SPHINXOPTS would only apply the flags to the `sphinx-build` command if you build the docs with `make html`, not if a user runs `sphinx-build` locally. Or am I misunderstanding something?

**Comment by niksirbi** [comment]
> Just to clarify, adding them to SPHINXOPTS would only apply the flags to the `sphinx-build` command when a user builds the docs with `make html`

Thanks for the clarifications. Then my initial suggestion for also adding these flags to the `sphinx-build` commands in the contributing guide still stands.

**Comment by sfmig** [comment]
Ok just to recap:
- the suggested flags have been added to contributing guide
- in the Makefile, the flags have been added via the SPHINXOPTS variable (as that seems to be its intended use; before I just appended the flags to the last `sphinx-build` command in the makefile)

This way both documented ways of building the docs locally (via make, or via explicit `sphinx-build` commands) match.

Thanks both!

**Pull request merged**
